/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author GW
 */
public class JpanRadar extends javax.swing.JPanel 
    {
    //--House Keeping
    private Color darkGreen;
    private double angle;
    double deltax;
    double deltay;
    int degrees;
    final int RADAR_SPPED = 5;
    public JpanRadar() 
    {
        initComponents();
        this.setBackground(Color.black);
        darkGreen = new Color(131, 179, 131);
        deltax = 0;
        deltay = 0;
    }

    @Override
    public void paintComponent(Graphics graph){
        super.paintComponent(graph); //To change body of generated methods, choose Tools | Templates.

        //--Draw the Radar Circles        
        graph.setColor(darkGreen);
        graph.drawOval(10, 10, getWidth() - 20 , getHeight() - 20);
        graph.drawOval(60, 60, getWidth() - 120 , getHeight() - 120);
        graph.drawOval(110, 110, getWidth() - 220 , getHeight() - 220);
        
        graph.drawLine(this.getWidth() / 2, this.getHeight() / 2, (int)deltax, (int) deltay);
        
    }
    
    public void Update(){
        /*degrees = ( ++degrees%360 == 0 ) ? 0 : degrees;
        angle = Math.toRadians(degrees);
        deltax = (Math.cos(angle) * deltax - Math.sin(angle) * deltay) + 100;
        deltay = (Math.sin(angle) * deltax + Math.cos(angle) * deltay) + 100;
        
        System.out.println("X: " + deltax);
        System.out.println("Y: " + deltay);
        System.out.println("Angle: " +angle);
        System.out.println("Degrees: " +degrees);
        System.out.println("Angle of Vector: " + (int)Math.toDegrees(Math.atan2(deltax, deltay)));*/
        if(deltax >= 0 && deltax < getWidth() && deltay <= 0){
            deltax+= RADAR_SPPED;
        }
        else if(deltax >= getWidth() && deltay >= 0 && deltay < getHeight()){
            deltay+=RADAR_SPPED;
        }
        else if(deltax <= getWidth() && deltax >= 0 && deltay >= getHeight()){
            deltax-=RADAR_SPPED;
        }
        else if(deltax <= 0 && deltay <= getHeight()){
            deltax = 0;
            deltay-=RADAR_SPPED;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
